In [2]:
# Voilà!!!

print("hello worlds 1")

hello worlds 1


In [3]:
import numpy as np
import scipy

array1d = np.array([0, 2, 4, 6, 8])
print(array1d)

[0 2 4 6 8]


In [4]:
array2d = np.array([[0, 2, 4], [6, 8, 10]])
print(array2d)

print(array2d[1, 0])

[[ 0  2  4]
 [ 6  8 10]]
6


In [5]:
print(type(array2d))

<class 'numpy.ndarray'>


In [6]:
print(array2d.shape)

(2, 3)


In [7]:
print(array2d[1, 2])

In [8]:
print(array2d[1, :1])

print(array2d[1, 1:])

# The results of these operations are a numpy array themselves

[6]
[ 8 10]


In [9]:
# cool ways to index numpy arrays
new2darray = np.array([[1,2,4,5,9],[3,4,6,6,10],[15,3,2,14,7]])
print(new2darray)


# Let's say you want the elements with indices [1,2], [0,4], [2,3]
newSubArray = new2darray[[1,0,2],[2,4,3]]
print(newSubArray)

[[ 1  2  4  5  9]
 [ 3  4  6  6 10]
 [15  3  2 14  7]]
[ 6  9 14]


In [10]:
# You can also index a boolean array
new2darray[new2darray > 10]

# new2darray > 10 return an array with the same size and shape of the original array

array([15, 14])

In [11]:
new2darray > 10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False,  True, False]], dtype=bool)

In [17]:
# You can create some standard arrays using built-in functions in numpy
# Ex: Arrays with all 0's, constant arrays, random numbers, etc

arrayOfZeros=np.zeros((2,2), dtype='int64')
print(arrayOfZeros)

arrayOfOnes=np.ones((2,2), dtype='int64')
print(arrayOfOnes)

arrayOfSevens=np.full((2,2), 7) # Fill a matrix with a constant value
print(arrayOfSevens)

identityMatrix = np.eye(3)
print(identityMatrix)

[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[[7 7]
 [7 7]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [19]:
# You can fill an array with random numbers

rndArray=np.random.random((2,2)) # Generates numbers in a uniform distribution from 0 to 1

print(rndArray)

[[ 0.90389888  0.80551531]
 [ 0.94679328  0.36052244]]


In [20]:
transposedArray = np.transpose(new2darray)

print(transposedArray)

[[ 1  3 15]
 [ 2  4  3]
 [ 4  6  2]
 [ 5  6 14]
 [ 9 10  7]]


In [21]:
# You can reshape arrays to any shape as long as the total number of elements remains the same

reshapedArray = np.reshape(new2darray, (1,15))
print(reshapedArray)

[[ 1  2  4  5  9  3  4  6  6 10 15  3  2 14  7]]


In [22]:
reshapedArray = np.reshape(reshapedArray, (15,1))
print(reshapedArray)

[[ 1]
 [ 2]
 [ 4]
 [ 5]
 [ 9]
 [ 3]
 [ 4]
 [ 6]
 [ 6]
 [10]
 [15]
 [ 3]
 [ 2]
 [14]
 [ 7]]


In [23]:
# Normal mathematical operations can be used to perform element-wise operations

array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[7,8,9],[3,2,1]])

print(array1 + array2)

[[ 8 10 12]
 [ 7  7  7]]


In [24]:
# You could use which are equivalent to the operations
np.subtract(array1,array2)

array([[-6, -6, -6],
       [ 1,  3,  5]])

In [25]:
# Broadcasting is a way in which you can add arrays of different dimensions
array3 = np.array([1,2,3])

array1 + array3 # This will add array 3 to each row of array1

array([[2, 4, 6],
       [5, 7, 9]])

In [ ]:
# To be able to broadcast, arrays need to be aligned along to at least 1 dimension

In [26]:
# One important operation you'll need to perform is the dot (inner product) of 2 array (remember, each row of the first matrix is
# multiplied by each column of the second matrix.

# To multiply, the number of columns of the left matrix must be equal to the number of rows of the right matrix

# In essence, the dot product represents a correlations, or how different two matrices are
np.dot(array1, array2) # won't work because both are 2x3

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [27]:
np.dot(array1, array2.T) # .T is a shortcut to the transpose of the array

array([[ 50,  10],
       [122,  28]])

In [28]:
# You can add or multiply all elements along one axis (like compressing an array)

np.sum(array1, axis=0)

array([5, 7, 9])

In [32]:
# merge arrays together with vstack or hstack

print(np.vstack((array1, array2)))
print(np.hstack((array1, array2)))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 2 1]]
[[1 2 3 7 8 9]
 [4 5 6 3 2 1]]


In [33]:
# Scipy has many modules to help us compute mathematical operations
# i.e. spatial module, given two points represented by np.arrays, scipy can help you
# find the distance between those two points
# The distance metric could be euclidean, cosine, correlation, hamming...

# pdist will compute pairwise distances between the rows in a numpy array

from scipy.spatial.distance import correlation, cosine, pdist, squareform

array1 = np.array([0,1,0])
array2 = np.array([1,0,0])

correlation(array1, array2)

1.5

In [36]:
allPoints = np.vstack((array1, array2))
d = squareform(pdist(allPoints, 'euclidean')) # Squareform will put the result in a nice, readable format

# The distance metric can be changed to cosine, correlation or any other distance. Check the complete list in
# scipy documentation

# This will compute the pairwise distance between all rows in allPoints
# d will be the square matrix d[i,j] being the Euclidean distance between allPoints[i,:] and allPoints[j,:]

print(d)

[[ 0.          1.41421356]
 [ 1.41421356  0.        ]]
