In [2]:
# Voilà!!!

print("hello worlds 1")

hello worlds 1


In [3]:
import numpy as np
import scipy

array1d = np.array([0, 2, 4, 6, 8])
print(array1d)

[0 2 4 6 8]


In [4]:
array2d = np.array([[0, 2, 4], [6, 8, 10]])
print(array2d)

print(array2d[1, 0])

[[ 0  2  4]
 [ 6  8 10]]
6


In [5]:
print(type(array2d))

<class 'numpy.ndarray'>


In [6]:
print(array2d.shape)

(2, 3)


In [7]:
print(array2d[1, 2])

In [8]:
print(array2d[1, :1])

print(array2d[1, 1:])

# The results of these operations are a numpy array themselves

[6]
[ 8 10]


In [9]:
# cool ways to index numpy arrays
new2darray = np.array([[1,2,4,5,9],[3,4,6,6,10],[15,3,2,14,7]])
print(new2darray)


# Let's say you want the elements with indices [1,2], [0,4], [2,3]
newSubArray = new2darray[[1,0,2],[2,4,3]]
print(newSubArray)

[[ 1  2  4  5  9]
 [ 3  4  6  6 10]
 [15  3  2 14  7]]
[ 6  9 14]


In [10]:
# You can also index a boolean array
new2darray[new2darray > 10]

# new2darray > 10 return an array with the same size and shape of the original array

array([15, 14])

In [11]:
new2darray > 10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False,  True, False]], dtype=bool)

In [17]:
# You can create some standard arrays using built-in functions in numpy
# Ex: Arrays with all 0's, constant arrays, random numbers, etc

arrayOfZeros=np.zeros((2,2), dtype='int64')
print(arrayOfZeros)

arrayOfOnes=np.ones((2,2), dtype='int64')
print(arrayOfOnes)

arrayOfSevens=np.full((2,2), 7) # Fill a matrix with a constant value
print(arrayOfSevens)

identityMatrix = np.eye(3)
print(identityMatrix)

[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[[7 7]
 [7 7]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [19]:
# You can fill an array with random numbers

rndArray=np.random.random((2,2)) # Generates numbers in a uniform distribution from 0 to 1

print(rndArray)

[[ 0.90389888  0.80551531]
 [ 0.94679328  0.36052244]]
